// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_graphicsview.cpp"
#include "EWIEGA46WW/moc_histogramwidget.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_spotdiagramwidget.cpp"
